# Week 6 Review: Variables, Data Types, and Collections
### Demystifying Python's Labeled Boxes using Policy & Economic Data

If programming terms like "variable assignment", "data types", or "dictionaries" sound like dry technical jargon, do not worry. 

Let us peel back the complex terminology and see how simple these concepts actually are under the hood, using real-world public policy and economic examples.

## 1. What is a Variable?

A variable is just a **labeled storage box**. 

- Imagine you are analyzing global markets and policies. 

    - You receive a report with the latest inflation rate for a country. 

    - Instead of typing the number over and over, you write it on a piece of paper, place it in a box, and write the sticker label "inflation_rate" on the outside. 

    - Whenever you need to run calculations, you tell Python to grab the box labeled "inflation_rate".

- In Python, we do this using the equals sign (`=`). 
    - **Crucial Tip**: In Python, `=` does not mean "equal to" in the mathematical sense. 
    - Instead, it is an instruction that says: **"Take whatever is on the right hand side and put it into the box labeled with the name on the left hand side."**

In [9]:
inflation_rate = 8

In [11]:
# We put the text "Japan" into a box labeled 'country_name'
country_name = "Japan"

# Now let us ask Python to show us what is inside the 'country_name' box
print(country_name)

Japan

In [12]:
country_name

'Japan'

### The Naming Rules for Your Storage Boxes
Python is very strict about what you can write on your box stickers. Follow these rules to avoid errors:

1.  **No Spaces**: Python gets confused by spaces. Use an underscore instead (e.g., `inflation_rate = 0.03` is perfect; `inflation rate = 0.03` will cause an error).
2.  **Case Sensitivity**: `gdp`, `Gdp`, and `GDP` are three completely different boxes. Be consistent!
3.  **No Numbers at the Start**: You can use numbers in your labels, but they cannot be the first character (e.g., `rate_2026` is fine, but `2026_rate` is illegal).
4.  **No Special Characters**: Keep it simple. Stick to letters, numbers, and underscores. Do not use symbols like `@`, `$`, or `-`.

In [16]:
#2026_rate = 9
rate_2026 = 9

## 2. What Goes Inside the Stoarge Box? (Data Types)

Just like you would store folders in one box, files in another, and pens in a smaller tray, Python stores different kinds of information in different ways. These are called **data types**.

Here are the four essential data types you will use every day in policy research:

*   **Text (Strings)**: Always wrapped in single or double quotes, e.g., `"United States"` or `'Democratic'`. 
    - Without quotes, Python thinks you are trying to call a variable box by that name and will look for a sticker!
*   **Whole Numbers (Integers)**: Numbers without decimal points, e.g., `4210` (representing GDP in billions).
*   **Decimals (Floats)**: Numbers with a decimal point, e.g., `0.026` (representing a 2.6% unemployment rate).
*   **Yes/No Decisions (Booleans)**: Can only be `True` or `False`. These must be capitalized, without quotes. Excellent for binary indicators like whether a nation is an OECD member.

In [25]:
# Let us create economic variables using different data types
country_name = "Japan"
gdp_in_billions = 4210
unemployment_rate = 0.026
is_oecd_member = False

import pandas as pd
data = pd.read_parquet("../../../data/examples/week_5/world_happiness.parquet").head(2)[['country_name', "ladder_score"]]

# Let us print out their values
print(country_name)
print(gdp_in_billions)
print(unemployment_rate)
print(is_oecd_member)
print(data)

Japan
4210
0.026
False
  country_name  ladder_score
0      Finland        7.7407
1      Denmark        7.5827

## 3. Organizing Multiple Items: Lists and Dictionaries

Sometimes, putting a single item in a box is not enough. You want to store a list of country names, or a folder with structured data. Python has special tools for this.

### A. Lists (An Ordered Tray)
A list is a single box containing several items arranged in a specific order. We use square brackets `[]` and separate items with commas.

> **Fun Python Fact**: Python starts counting positions at **0**, not 1! So the first item in a list is at index 0, the second is at index 1, and so on.

In [ ]:
# A list of G7 member nations
g7_countries = ["Canada", "France", "Germany", "Italy", "Japan"]

# Print the whole list
print(g7_countries)

# Print the FIRST nation (at index 0)
print(g7_countries[0])

[3, 46.66]
3

### B. Dictionaries (A Labeled Folder)
A dictionary is like a folder with custom labeled tabs. Instead of looking up items by their index position (0, 1, 2), you look them up using a **key** (the tab label) to get the **value** associated with it.

We use curly braces `{}` and pair a key with a value using a colon `:`.

In [30]:
# A country indicator dictionary containing 3 pieces of information
country_profile = {
    "country": "Mexico",
    "inflation_rate": 0.044,
    "is_democratic": True
}

# Print the whole dictionary
print(country_profile)

# Look up the inflation rate key to see Mexico's inflation
print(country_profile["inflation_rate"])

{'country': 'Mexico', 'inflation_rate': 0.044, 'is_democratic': True}
0.044

In [35]:
data

  country_name  ladder_score
0      Finland        7.7407
1      Denmark        7.5827

In [38]:
rename_dictionary = {"country_name": "country"}
data.rename(rename_dictionary, axis='columns')

   country  ladder_score
0  Finland        7.7407
1  Denmark        7.5827

## 4. Reassigning Variables

Remember: a variable is just a box. You can open it, throw out the old contents, and put in something brand new whenever you want. Python will always remember the **most recent** thing you put inside. 

Let us simulate an increase in the hourly federal minimum wage policy:

In [39]:
# Set the starting minimum wage variable
minimum_wage = 15.00
print(minimum_wage)

# A new policy wage hike goes into effect!
minimum_wage = 16.50
print(minimum_wage)

15.0
16.5

In [41]:
# Set the starting minimum wage variable
minimum_wage = 15.00


# A new policy wage hike goes into effect!
minimum_wage = 16.50
minimum_wage

16.5